logging:
  level:
    root: info
    com.elbigs: info

spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:49153/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: qwerasdf4$
    platform: all
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
          format_sql: true  #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
          use_sql_comments: true #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
  url:
    base: http://localhost:8080
  config:
    activate:
      on-profile: local

#Azure Blob Storage settings
blob:
  storage-url: https://gds-cdn.azureedge.net/dev-images
  container-name: dev-images
  account-name: sjangds
  account-key: Jopdk4SDzmdymKtUQ5wMLBUfhglSRRynU1gsT+Aw0N2j8oOuzRd4W9N2q1kIBUhrypa7kLzD3mki8EE+C5PuyA==
  default-endpoints-protocol: https

file:
  connectable-type-shop: App\Models\Shop
  connectable-type-facility: App\Models\Facility
  connectable-type-tourism: App\Models\Tourism
  connectable-type-event: App\Models\Event
  connectable-type-lineNotice: App\Models\LineNotice
  connectable-type-setting: App\Models\Setting
  connectable-type-notice: App\Models\Notice
  connectable-type-message: App\Models\Message
  connectable-type-qna: App\Models\Qna
  connectable-type-adver: App\Models\AdDetail

weather:
  service-key: cfb5/nlGD1Pn1T9sIp6162DJW87nj0W4PHsn9sooKE6WD8pIM54BGnWQxtn7Ufk5gxIsr6y0UqYGqLZFUKD4kw==




